# docker-compose up --detach
# docker-compose down --volumes

version: "2.4"
services:
  lnx-deb-img:
    volumes:
    - "./:/home/iamamutt/lnx-deb-image"
    image: ghcr.io/iamamutt/lnx-deb-image:latest # lnx-deb-image:v0.0.0a
    init: true
    tty: true
