name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.0a

      - name: Get current date
        id: timestamp
        run: echo "::set-output name=date::$(date -d @${{ steps.previoustag.outputs.timestamp }} +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:buildx-stable-1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            IMAGE_CREATED=${{ steps.timestamp.outputs.date }}
            IMAGE_VERSION=${{ steps.previoustag.outputs.tag }}
            USER_NAME=${{ github.actor }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./build/debian
          file: ./build/debian/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lnx-deb-image:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/lnx-deb-image:${{ steps.previoustag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/lnx-deb-image:latest
            ghcr.io/${{ github.repository_owner }}/lnx-deb-image:${{ steps.previoustag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
