on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag
        id: set-tag
        run: |
          echo ::set-output name=head_ref::${GITHUB_REF##*/}
          git fetch --prune --unshallow
          echo "::set-output name=last_tag::$(git describe --tags --abbrev=0)"
      - name: Print Tag
        env:
          HEAD_REF: ${{ steps.set-tag.outputs.head_ref }}
        run: |
          echo $HEAD_REF
          echo ${{ steps.set-tag.outputs.head_ref }}
          echo ${{ steps.set-tag.outputs.last_tag }}
